import { createHash, randomUUID } from 'node:crypto';
import { constants, type Stats } from 'node:fs';
import { lstat, open, stat, type FileHandle } from 'node:fs/promises';
import path from 'node:path';

import { VaultaError } from '../../shared/errors';
import { type AttachmentMetadata, type VaultDocument } from '../../shared/models';
import { CryptoService, type AesGcmEnvelope } from '../security/crypto-service';
import { KeyDerivationService, type Argon2idParameters } from '../security/key-derivation';
import { AtomicFileWriter } from '../storage/atomic-file';
import { assertSafeIdentifier } from '../storage/path-safety';
import { isSafeAttachmentPreviewMediaType, type AttachmentService } from './attachment-service';
import {
  parseVaultDocumentV2,
  repairHistoricalV2DocumentMissingLifecycle,
  type VaultService,
} from './vault-service';

/**
 * Portable vault packages deliberately use a format which is unrelated to a
 * profile backup.  The values below are local to this service so a package can
 * neither accidentally be mistaken for a backup nor inherit its access model.
 */
const PACKAGE_MAGIC = Buffer.from('KRYVLT01', 'ascii');
export const VAULT_PACKAGE_FORMAT_VERSION = 1 as const;
export const VAULT_PACKAGE_EXTENSION = '.kryptris-vault';
const CHUNK_SIZE = 1024 * 1024;
const HEADER_LIMIT = 64 * 1024;
const MAX_METADATA_RECORD_BYTES = 32 * 1024 * 1024;
const MAX_ATTACHMENT_BYTES = 100 * 1024 * 1024;
const DEFAULT_MAX_TOTAL_ATTACHMENT_BYTES = 512 * 1024 * 1024;
const RECORD_HEADER_BYTES = 9;
const TAG_BYTES = 16;
const DOCUMENT_RECORD = 0;
const ATTACHMENT_START_RECORD = 1;
const ATTACHMENT_DATA_RECORD = 2;
const ATTACHMENT_END_RECORD = 3;
const MANIFEST_RECORD = 4;
const UUID_V4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
const SHA256 = /^[0-9a-f]{64}$/u;
const ATOMIC_PACKAGE_TEMPORARY =
  /^\..+\.kryptris-vault\.vaulta-tmp-[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;

interface VaultPackageHeader {
  readonly format: 'kryptris-vault-package';
  readonly version: typeof VAULT_PACKAGE_FORMAT_VERSION;
  readonly packageId: string;
  readonly createdAt: string;
  readonly cipher: 'AES-256-GCM-CHUNKED';
  readonly chunkSize: typeof CHUNK_SIZE;
  readonly noncePrefix: string;
  readonly kdf: {
    readonly algorithm: 'argon2id';
    readonly salt: string;
    readonly parameters: Argon2idParameters;
  };
  readonly wrappedPackageKey: AesGcmEnvelope;
}

interface VaultPackageDocumentDescriptor {
  readonly size: number;
  readonly sha256: string;
}

interface VaultPackageAttachmentDescriptor {
  readonly id: string;
  readonly size: number;
  readonly sha256: string;
}

interface VaultPackageManifest {
  readonly format: 'kryptris-vault-package-manifest';
  readonly version: typeof VAULT_PACKAGE_FORMAT_VERSION;
  readonly packageId: string;
  readonly exportedAt: string;
  readonly includesAttachments: boolean;
  readonly document: VaultPackageDocumentDescriptor;
  readonly attachments: readonly VaultPackageAttachmentDescriptor[];
  readonly rootSha256: string;
}

interface PackageAttachmentStart {
  readonly id: string;
  readonly metadata: AttachmentMetadata;
}

interface PackageAttachmentEnd {
  readonly id: string;
  readonly size: number;
  readonly sha256: string;
}

interface DecodedAttachment {
  readonly metadata: AttachmentMetadata;
  readonly plaintext: Buffer;
}

interface PendingAttachment {
  readonly metadata: AttachmentMetadata;
  readonly chunks: Buffer[];
  readonly size: number;
  readonly hash: ReturnType<typeof createHash>;
}

interface FileIdentity {
  readonly dev: number;
  readonly ino: number;
  readonly size: number;
  readonly mtimeMs: number;
  readonly ctimeMs: number;
}

interface DecodedPackage {
  readonly header: VaultPackageHeader;
  readonly document: VaultDocument;
  readonly attachments: DecodedAttachment[];
  readonly manifest: VaultPackageManifest;
}

export interface VaultPackageServiceOptions {
  readonly vaultService: VaultService;
  readonly attachmentService: AttachmentService;
  readonly crypto?: CryptoService;
  readonly keyDerivation?: KeyDerivationService;
  readonly atomicWriter?: AtomicFileWriter;
  readonly now?: () => Date;
  /**
   * The importer intentionally keeps decrypted attachment data in Main-process
   * memory until the caller's one-shot transactional installer has consumed it.
   * A finite aggregate bound prevents a malicious package from exhausting RAM.
   */
  readonly maximumTotalAttachmentBytes?: number;
  /** Test seam; production uses UUIDv4 values generated by Node. */
  readonly generateId?: () => string;
}

export interface ExportVaultPackageInput {
  readonly vaultId: string;
  readonly exportPassword: string;
  readonly destination: string;
  readonly includeAttachments: boolean;
  readonly replaceExisting?: boolean;
  /** Checked repeatedly by the controller's session epoch while exporting. */
  readonly assertAuthorized?: () => void;
}

export interface VaultPackageExportResult {
  readonly path: string;
  readonly createdAt: string;
  readonly entryCount: number;
  readonly attachmentCount: number;
  readonly includesAttachments: boolean;
}

/** Only redacted, renderer-safe values are exposed by a package preview. */
export interface VaultPackagePreview {
  readonly createdAt: string;
  readonly vaultName: string;
  readonly color: string;
  readonly entryCount: number;
  readonly attachmentCount: number;
  readonly includesAttachments: boolean;
  readonly nameConflict: boolean;
}

export interface InspectVaultPackageInput {
  readonly packagePath: string;
  readonly exportPassword: string;
  readonly existingVaultNames?: readonly string[];
  readonly assertAuthorized?: () => void;
}

export interface PrepareVaultPackageImportInput extends InspectVaultPackageInput {
  /** A new, already-reserved local vault id; it must never equal the source id. */
  readonly targetVaultId: string;
  /** A user-confirmed target name. It is checked against existing names again. */
  readonly targetVaultName: string;
  readonly allowNameConflict?: boolean;
}

/**
 * Main-process-only attachment payload handed to the atomic import coordinator.
 * `plaintext` must be re-encrypted immediately under the newly generated target
 * vault key and erased by the coordinator (or by `dispose`) on every exit path.
 */
export interface PreparedVaultPackageAttachment {
  readonly attachmentId: string;
  readonly name: string;
  readonly mediaType: string;
  readonly size: number;
  readonly sha256: string;
  readonly createdAt: string;
  readonly previewable: boolean;
  readonly contents: Buffer;
}

/**
 * A fully authenticated, re-identified import plan. It does not write any
 * profile, vault, or attachment file: the controller must install all values in
 * one multi-file transaction with a freshly generated target vault key.
 */
export class PreparedVaultPackageImport {
  public readonly document: VaultDocument;
  public readonly attachments: readonly PreparedVaultPackageAttachment[];
  public readonly preview: VaultPackagePreview;
  private disposed = false;

  public constructor(
    document: VaultDocument,
    attachments: readonly PreparedVaultPackageAttachment[],
    preview: VaultPackagePreview,
    private readonly crypto: CryptoService,
  ) {
    this.document = document;
    this.attachments = attachments;
    this.preview = preview;
  }

  /** Idempotently erases the package-owned attachment plaintext buffers. */
  public dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    for (const attachment of this.attachments) this.crypto.erase(attachment.contents);
  }

  public assertUsable(): void {
    if (this.disposed) {
      throw new VaultaError('CONFLICT', 'Der vorbereitete Tresorimport wurde bereits verworfen.');
    }
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function parseJson(bytes: Buffer, message: string): unknown {
  try {
    return JSON.parse(bytes.toString('utf8')) as unknown;
  } catch (error) {
    throw new VaultaError('CORRUPT_DATA', message, null, { cause: error });
  }
}

function readPackageDocumentId(value: unknown): string {
  if (!isRecord(value) || typeof value.id !== 'string') {
    throw new VaultaError('CORRUPT_DATA', 'Der Tresorinhalt im Paket ist ungueltig.');
  }
  assertSafeIdentifier(value.id, 'Tresor-ID');
  return value.id;
}

/**
 * Parses an already authenticated package payload. Early Welle-8 development
 * packages could mark a document as V2 before they persisted the neutral
 * lifecycle block for every older entry. The shared compatibility repair is
 * deliberately narrower than a generic V2 normalizer: it accepts only a
 * strict V1 projection, fills only entirely missing lifecycle properties, and
 * still runs the final current V2 parser. Existing lifecycle values remain
 * intact, so partial, malformed, or semantically invalid values stay rejected.
 */
export function parseAuthenticatedVaultPackageDocument(value: unknown): VaultDocument {
  const expectedId = readPackageDocumentId(value);
  try {
    return parseVaultDocumentV2(value, expectedId);
  } catch (error) {
    const repaired = repairHistoricalV2DocumentMissingLifecycle(value, expectedId);
    if (repaired !== null) return repaired;
    throw error;
  }
}

function parseEnvelope(value: unknown): AesGcmEnvelope {
  if (
    !isRecord(value) ||
    value.algorithm !== 'AES-256-GCM' ||
    typeof value.nonce !== 'string' ||
    typeof value.ciphertext !== 'string' ||
    typeof value.tag !== 'string'
  ) {
    throw new VaultaError('CORRUPT_DATA', 'Der Paketschluessel-Umschlag ist ungueltig.');
  }
  return {
    algorithm: 'AES-256-GCM',
    nonce: value.nonce,
    ciphertext: value.ciphertext,
    tag: value.tag,
  };
}

function assertIsoTimestamp(value: unknown, message: string): asserts value is string {
  if (typeof value !== 'string' || Number.isNaN(Date.parse(value))) {
    throw new VaultaError('CORRUPT_DATA', message);
  }
}

function assertPositiveSafeInteger(value: unknown, message: string): asserts value is number {
  if (!Number.isSafeInteger(value) || (value as number) < 0) {
    throw new VaultaError('CORRUPT_DATA', message);
  }
}

function writeAll(handle: FileHandle, data: Buffer, position: number): Promise<number> {
  return (async () => {
    let written = 0;
    while (written < data.length) {
      const result = await handle.write(data, written, data.length - written, position + written);
      if (result.bytesWritten === 0) throw new Error('Could not make progress writing package');
      written += result.bytesWritten;
    }
    return position + written;
  })();
}

async function readExact(handle: FileHandle, length: number, position: number): Promise<Buffer> {
  const buffer = Buffer.allocUnsafe(length);
  try {
    let read = 0;
    while (read < length) {
      const result = await handle.read(buffer, read, length - read, position + read);
      if (result.bytesRead === 0) {
        throw new VaultaError('CORRUPT_DATA', 'Das Tresor-Paket ist unvollstaendig.');
      }
      read += result.bytesRead;
    }
    return buffer;
  } catch (error) {
    buffer.fill(0);
    throw error;
  }
}

function sameAttachmentMetadata(left: AttachmentMetadata, right: AttachmentMetadata): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

function normalizedName(value: string): string {
  return value.trim().toLocaleLowerCase('de-DE');
}

function fileIdentity(info: Stats): FileIdentity {
  return {
    dev: info.dev,
    ino: info.ino,
    size: info.size,
    mtimeMs: info.mtimeMs,
    ctimeMs: info.ctimeMs,
  };
}

function sameIdentity(left: FileIdentity, right: FileIdentity): boolean {
  return (
    left.dev === right.dev &&
    left.ino === right.ino &&
    left.size === right.size &&
    left.mtimeMs === right.mtimeMs &&
    left.ctimeMs === right.ctimeMs
  );
}

function decodeBase64Strict(value: string, expectedBytes: number, message: string): Buffer {
  if (!/^[A-Za-z0-9+/]*={0,2}$/u.test(value) || value.length % 4 !== 0) {
    throw new VaultaError('CORRUPT_DATA', message);
  }
  const decoded = Buffer.from(value, 'base64');
  if (decoded.length !== expectedBytes || decoded.toString('base64') !== value) {
    decoded.fill(0);
    throw new VaultaError('CORRUPT_DATA', message);
  }
  return decoded;
}

/**
 * Implements ADR-0007's independent portable package format. It is deliberately
 * non-persistent apart from the encrypted package file: importing only produces
 * a fully validated plan for the controller's atomic installer.
 */
export class VaultPackageService {
  private readonly crypto: CryptoService;
  private readonly keyDerivation: KeyDerivationService;
  private readonly atomicWriter: AtomicFileWriter;
  private readonly now: () => Date;
  private readonly maximumTotalAttachmentBytes: number;
  private readonly generateId: () => string;

  public constructor(private readonly options: VaultPackageServiceOptions) {
    this.crypto = options.crypto ?? new CryptoService();
    this.keyDerivation = options.keyDerivation ?? new KeyDerivationService();
    this.atomicWriter = options.atomicWriter ?? new AtomicFileWriter();
    this.now = options.now ?? (() => new Date());
    this.maximumTotalAttachmentBytes =
      options.maximumTotalAttachmentBytes ?? DEFAULT_MAX_TOTAL_ATTACHMENT_BYTES;
    this.generateId = options.generateId ?? randomUUID;
    if (
      !Number.isSafeInteger(this.maximumTotalAttachmentBytes) ||
      this.maximumTotalAttachmentBytes < 0 ||
      this.maximumTotalAttachmentBytes > Number.MAX_SAFE_INTEGER
    ) {
      throw new VaultaError('INVALID_INPUT', 'Das Paket-Anhangslimit ist ungueltig.');
    }
  }

  public async exportPackage(input: ExportVaultPackageInput): Promise<VaultPackageExportResult> {
    try {
      this.assertExportInput(input);
      return await this.options.vaultService.withExclusiveVaults([input.vaultId], async () => {
        input.assertAuthorized?.();
        return this.exportLocked(input);
      });
    } catch (error) {
      throw this.redactUnexpectedError(error, 'Das Tresor-Paket konnte nicht exportiert werden.');
    }
  }

  public async inspectPackage(input: InspectVaultPackageInput): Promise<VaultPackagePreview> {
    let decoded: DecodedPackage | null = null;
    try {
      this.assertInspectionInput(input);
      decoded = await this.decodePackage(
        input.packagePath,
        input.exportPassword,
        input.assertAuthorized,
      );
      input.assertAuthorized?.();
      return this.toPreview(decoded, input.existingVaultNames ?? []);
    } catch (error) {
      throw this.redactUnexpectedError(error, 'Das Tresor-Paket konnte nicht geprueft werden.');
    } finally {
      this.disposeDecoded(decoded);
    }
  }

  public async prepareImport(
    input: PrepareVaultPackageImportInput,
  ): Promise<PreparedVaultPackageImport> {
    let decoded: DecodedPackage | null = null;
    let transferred = false;
    try {
      this.assertInspectionInput(input);
      assertSafeIdentifier(input.targetVaultId, 'Ziel-Tresor-ID');
      const targetName = this.validateVaultName(input.targetVaultName);
      decoded = await this.decodePackage(
        input.packagePath,
        input.exportPassword,
        input.assertAuthorized,
      );
      input.assertAuthorized?.();
      if (decoded.document.id === input.targetVaultId) {
        throw new VaultaError('CONFLICT', 'Der Ziel-Tresor muss eine neue technische ID erhalten.');
      }

      const preview = this.toPreview(decoded, input.existingVaultNames ?? []);
      if (
        input.allowNameConflict !== true &&
        (input.existingVaultNames ?? []).some(
          (name) => normalizedName(name) === normalizedName(targetName),
        )
      ) {
        throw new VaultaError(
          'CONFLICT',
          'Ein Tresor mit dem gewaehlten Zielnamen existiert bereits.',
        );
      }

      const remapped = this.reidentifyDocument(
        decoded.document,
        decoded.attachments,
        input.targetVaultId,
        targetName,
      );
      input.assertAuthorized?.();
      const attachments = remapped.attachments;
      const plan = new PreparedVaultPackageImport(
        remapped.document,
        attachments,
        preview,
        this.crypto,
      );
      transferred = true;
      return plan;
    } catch (error) {
      throw this.redactUnexpectedError(error, 'Das Tresor-Paket konnte nicht vorbereitet werden.');
    } finally {
      if (!transferred) this.disposeDecoded(decoded);
    }
  }

  private async exportLocked(input: ExportVaultPackageInput): Promise<VaultPackageExportResult> {
    const destination = await this.resolveExportDestination(
      input.destination,
      input.replaceExisting,
    );
    const source = await this.options.vaultService.readVaultFresh(input.vaultId, () =>
      input.assertAuthorized?.(),
    );
    input.assertAuthorized?.();
    const document = this.documentForExport(source, input.includeAttachments);
    const attachmentMetadata = this.collectDocumentAttachments(document);
    const createdAt = this.now().toISOString();
    const packageId = this.nextPackageId();
    const noncePrefix = this.crypto.randomBytes(8);
    const salt = this.crypto.randomBytes(16);
    let passwordKey: Buffer | null = null;
    let packageKey: Buffer | null = null;
    let headerBytes: Buffer | null = null;
    let documentBytes: Buffer | null = null;
    try {
      const parameters = await this.keyDerivation.calibrate();
      input.assertAuthorized?.();
      passwordKey = await this.keyDerivation.derive(input.exportPassword, salt, parameters);
      packageKey = this.crypto.randomBytes(32);
      const header: VaultPackageHeader = {
        format: 'kryptris-vault-package',
        version: VAULT_PACKAGE_FORMAT_VERSION,
        packageId,
        createdAt,
        cipher: 'AES-256-GCM-CHUNKED',
        chunkSize: CHUNK_SIZE,
        noncePrefix: noncePrefix.toString('base64'),
        kdf: {
          algorithm: 'argon2id',
          salt: salt.toString('base64'),
          parameters,
        },
        wrappedPackageKey: this.crypto.wrapKey(
          packageKey,
          passwordKey,
          this.packageKeyContext(packageId),
        ),
      };
      headerBytes = Buffer.from(JSON.stringify(header), 'utf8');
      this.parseHeader(parseJson(headerBytes, 'Der erzeugte Paketheader ist ungueltig.'));
      documentBytes = Buffer.from(JSON.stringify(document), 'utf8');
      if (documentBytes.length > MAX_METADATA_RECORD_BYTES) {
        throw new VaultaError(
          'FILE_TOO_LARGE',
          'Der Tresor ist fuer ein portables Paket zu gross.',
        );
      }
      const documentDescriptor = this.descriptor(documentBytes);
      const manifestAttachments: VaultPackageAttachmentDescriptor[] = [];

      await this.atomicWriter.writeGenerated(
        destination,
        async (output) => {
          let position = 0;
          let recordIndex = 0;
          position = await writeAll(output, PACKAGE_MAGIC, position);
          const headerLength = Buffer.allocUnsafe(4);
          try {
            headerLength.writeUInt32BE(headerBytes!.length, 0);
            position = await writeAll(output, headerLength, position);
          } finally {
            this.crypto.erase(headerLength);
          }
          position = await writeAll(output, headerBytes!, position);
          position = await this.writeRecord(
            output,
            position,
            DOCUMENT_RECORD,
            recordIndex++,
            documentBytes!,
            packageKey!,
            noncePrefix,
            headerBytes!,
          );

          for (const metadata of attachmentMetadata) {
            input.assertAuthorized?.();
            await this.options.attachmentService.verifyMetadata(input.vaultId, metadata, () =>
              input.assertAuthorized?.(),
            );
            input.assertAuthorized?.();
            const start = Buffer.from(
              JSON.stringify({ id: metadata.id, metadata } satisfies PackageAttachmentStart),
              'utf8',
            );
            let plaintext: Buffer | null = null;
            try {
              position = await this.writeRecord(
                output,
                position,
                ATTACHMENT_START_RECORD,
                recordIndex++,
                start,
                packageKey!,
                noncePrefix,
                headerBytes!,
              );
              plaintext = await this.options.attachmentService.readBuffer(
                input.vaultId,
                metadata.id,
                MAX_ATTACHMENT_BYTES,
              );
              input.assertAuthorized?.();
              if (plaintext.length !== metadata.size) {
                throw new VaultaError(
                  'CORRUPT_DATA',
                  'Ein Anhang stimmt nicht mit seinen Metadaten ueberein.',
                );
              }
              const sha256 = this.crypto.sha256(plaintext).toString('hex');
              if (sha256 !== metadata.sha256) {
                throw new VaultaError(
                  'CORRUPT_DATA',
                  'Ein Anhang stimmt nicht mit seinen Metadaten ueberein.',
                );
              }
              for (let offset = 0; offset < plaintext.length; offset += CHUNK_SIZE) {
                input.assertAuthorized?.();
                position = await this.writeRecord(
                  output,
                  position,
                  ATTACHMENT_DATA_RECORD,
                  recordIndex++,
                  plaintext.subarray(offset, Math.min(offset + CHUNK_SIZE, plaintext.length)),
                  packageKey!,
                  noncePrefix,
                  headerBytes!,
                );
              }
              const end = Buffer.from(
                JSON.stringify({
                  id: metadata.id,
                  size: plaintext.length,
                  sha256,
                } satisfies PackageAttachmentEnd),
                'utf8',
              );
              try {
                position = await this.writeRecord(
                  output,
                  position,
                  ATTACHMENT_END_RECORD,
                  recordIndex++,
                  end,
                  packageKey!,
                  noncePrefix,
                  headerBytes!,
                );
              } finally {
                this.crypto.erase(end);
              }
              manifestAttachments.push({ id: metadata.id, size: plaintext.length, sha256 });
            } finally {
              this.crypto.erase(start);
              this.crypto.erase(plaintext);
            }
          }

          const manifest: VaultPackageManifest = {
            format: 'kryptris-vault-package-manifest',
            version: VAULT_PACKAGE_FORMAT_VERSION,
            packageId,
            exportedAt: createdAt,
            includesAttachments: input.includeAttachments,
            document: documentDescriptor,
            attachments: manifestAttachments,
            rootSha256: this.manifestRootHash(documentDescriptor, manifestAttachments),
          };
          const manifestBytes = Buffer.from(JSON.stringify(manifest), 'utf8');
          try {
            await this.writeRecord(
              output,
              position,
              MANIFEST_RECORD,
              recordIndex,
              manifestBytes,
              packageKey!,
              noncePrefix,
              headerBytes!,
            );
          } finally {
            this.crypto.erase(manifestBytes);
          }
        },
        async (temporaryPath) => {
          const inspected = await this.decodePackage(
            temporaryPath,
            input.exportPassword,
            input.assertAuthorized,
            true,
          );
          try {
            if (
              inspected.header.packageId !== packageId ||
              inspected.manifest.document.sha256 !== documentDescriptor.sha256 ||
              inspected.manifest.attachments.length !== manifestAttachments.length
            ) {
              throw new VaultaError(
                'CORRUPT_DATA',
                'Das erzeugte Tresor-Paket ist unvollstaendig.',
              );
            }
          } finally {
            this.disposeDecoded(inspected);
          }
        },
        async (targetPath) => {
          await this.assertSafeExportTarget(targetPath, input.replaceExisting);
          input.assertAuthorized?.();
        },
      );
      return {
        path: destination,
        createdAt,
        entryCount: document.entries.length,
        attachmentCount: manifestAttachments.length,
        includesAttachments: input.includeAttachments,
      };
    } finally {
      this.crypto.erase(documentBytes);
      this.crypto.erase(headerBytes);
      this.crypto.erase(packageKey);
      this.crypto.erase(passwordKey);
      this.crypto.erase(salt);
      this.crypto.erase(noncePrefix);
    }
  }

  private async decodePackage(
    packagePath: string,
    exportPassword: string,
    assertAuthorized: (() => void) | undefined,
    allowAtomicTemporary = false,
  ): Promise<DecodedPackage> {
    const expectedFile = await this.assertRegularPackagePath(packagePath, allowAtomicTemporary);
    const input = await open(expectedFile.path, constants.O_RDONLY);
    let passwordKey: Buffer | null = null;
    let packageKey: Buffer | null = null;
    let headerBytes: Buffer | null = null;
    let documentBytes: Buffer | null = null;
    let kdfSalt: Buffer | null = null;
    const attachments: DecodedAttachment[] = [];
    let currentAttachment: PendingAttachment | null = null;
    let completed = false;
    try {
      assertAuthorized?.();
      const info = await input.stat();
      await this.assertOpenedPackageMatches(expectedFile, info);
      const parsedHeader = await this.readHeader(input);
      headerBytes = parsedHeader.headerBytes;
      kdfSalt = decodeBase64Strict(
        parsedHeader.header.kdf.salt,
        16,
        'Der Paket-KDF-Salt ist ungueltig.',
      );
      passwordKey = await this.keyDerivation.derive(
        exportPassword,
        kdfSalt,
        parsedHeader.header.kdf.parameters,
      );
      try {
        packageKey = this.crypto.unwrapKey(
          parsedHeader.header.wrappedPackageKey,
          passwordKey,
          this.packageKeyContext(parsedHeader.header.packageId),
        );
      } catch (error) {
        throw new VaultaError('AUTH_FAILED', 'Das Exportpasswort ist falsch.', null, {
          cause: error,
        });
      }
      const noncePrefix = Buffer.from(parsedHeader.header.noncePrefix, 'base64');
      try {
        let position = parsedHeader.dataOffset;
        let expectedIndex = 0;
        let manifest: VaultPackageManifest | null = null;
        const observedAttachments: VaultPackageAttachmentDescriptor[] = [];
        let documentDescriptor: VaultPackageDocumentDescriptor | null = null;
        let totalAttachmentBytes = 0;

        while (position < info.size) {
          assertAuthorized?.();
          const recordHeader = await readExact(input, RECORD_HEADER_BYTES, position);
          position += RECORD_HEADER_BYTES;
          const type = recordHeader.readUInt8(0);
          const index = recordHeader.readUInt32BE(1);
          const ciphertextLength = recordHeader.readUInt32BE(5);
          this.crypto.erase(recordHeader);
          if (index !== expectedIndex || type > MANIFEST_RECORD) {
            throw new VaultaError(
              'CORRUPT_DATA',
              'Die Paketdatensaetze sind vertauscht oder ungueltig.',
            );
          }
          const maximum = type === ATTACHMENT_DATA_RECORD ? CHUNK_SIZE : MAX_METADATA_RECORD_BYTES;
          if (ciphertextLength > maximum) {
            throw new VaultaError('CORRUPT_DATA', 'Ein Paketdatensatz ist zu gross.');
          }
          const tag = await readExact(input, TAG_BYTES, position);
          position += TAG_BYTES;
          const ciphertext = await readExact(input, ciphertextLength, position);
          position += ciphertextLength;
          const nonce = this.recordNonce(noncePrefix, index);
          const aad = this.recordAad(headerBytes, type, index);
          let plaintext: Buffer | null = null;
          try {
            plaintext = this.crypto.decrypt(
              {
                algorithm: 'AES-256-GCM',
                nonce: nonce.toString('base64'),
                ciphertext: ciphertext.toString('base64'),
                tag: tag.toString('base64'),
              },
              packageKey,
              aad,
            );
            assertAuthorized?.();
            if (type === DOCUMENT_RECORD) {
              if (documentBytes !== null || currentAttachment !== null || manifest !== null) {
                throw new VaultaError(
                  'CORRUPT_DATA',
                  'Der Tresorinhalt steht an einer ungueltigen Stelle.',
                );
              }
              documentBytes = Buffer.from(plaintext);
              documentDescriptor = this.descriptor(documentBytes);
            } else if (type === ATTACHMENT_START_RECORD) {
              if (documentBytes === null || currentAttachment !== null || manifest !== null) {
                throw new VaultaError(
                  'CORRUPT_DATA',
                  'Der Anhangsanfang steht an einer ungueltigen Stelle.',
                );
              }
              const start = this.parseAttachmentStart(
                parseJson(plaintext, 'Der Anhangsanfang ist ungueltig.'),
              );
              if (attachments.some((attachment) => attachment.metadata.id === start.id)) {
                throw new VaultaError('CORRUPT_DATA', 'Das Paket enthaelt doppelte Anhangs-IDs.');
              }
              totalAttachmentBytes += start.metadata.size;
              if (totalAttachmentBytes > this.maximumTotalAttachmentBytes) {
                throw new VaultaError(
                  'FILE_TOO_LARGE',
                  'Die Anhaenge dieses Tresor-Pakets ueberschreiten das unterstuetzte Gesamtlimit.',
                );
              }
              currentAttachment = {
                metadata: start.metadata,
                chunks: [],
                size: 0,
                hash: createHash('sha256'),
              };
            } else if (type === ATTACHMENT_DATA_RECORD) {
              if (currentAttachment === null || manifest !== null) {
                throw new VaultaError('CORRUPT_DATA', 'Ein Anhangschunk besitzt keinen Anhang.');
              }
              const activeAttachment: PendingAttachment = currentAttachment;
              if (activeAttachment.size + plaintext.length > activeAttachment.metadata.size) {
                throw new VaultaError('CORRUPT_DATA', 'Ein Anhang ist groesser als angekuendigt.');
              }
              activeAttachment.hash.update(plaintext);
              activeAttachment.chunks.push(Buffer.from(plaintext));
              currentAttachment = {
                metadata: activeAttachment.metadata,
                chunks: activeAttachment.chunks,
                hash: activeAttachment.hash,
                size: activeAttachment.size + plaintext.length,
              };
            } else if (type === ATTACHMENT_END_RECORD) {
              if (currentAttachment === null || manifest !== null) {
                throw new VaultaError(
                  'CORRUPT_DATA',
                  'Ein Anhangsabschluss besitzt keinen Anhang.',
                );
              }
              const end = this.parseAttachmentEnd(
                parseJson(plaintext, 'Der Anhangsabschluss ist ungueltig.'),
              );
              const sha256 = currentAttachment.hash.digest('hex');
              if (
                end.id !== currentAttachment.metadata.id ||
                end.size !== currentAttachment.size ||
                end.sha256 !== sha256 ||
                currentAttachment.size !== currentAttachment.metadata.size ||
                sha256 !== currentAttachment.metadata.sha256
              ) {
                throw new VaultaError(
                  'CORRUPT_DATA',
                  'Ein Anhang stimmt nicht mit seinem Abschluss ueberein.',
                );
              }
              const joined = Buffer.concat(currentAttachment.chunks, currentAttachment.size);
              for (const chunk of currentAttachment.chunks) this.crypto.erase(chunk);
              attachments.push({ metadata: currentAttachment.metadata, plaintext: joined });
              observedAttachments.push({
                id: currentAttachment.metadata.id,
                size: currentAttachment.size,
                sha256,
              });
              currentAttachment = null;
            } else {
              if (
                documentBytes === null ||
                documentDescriptor === null ||
                currentAttachment !== null ||
                manifest !== null ||
                position !== info.size
              ) {
                throw new VaultaError(
                  'CORRUPT_DATA',
                  'Das Paketmanifest steht nicht am Dateiende.',
                );
              }
              manifest = this.parseManifest(
                parseJson(plaintext, 'Das Paketmanifest ist ungueltig.'),
              );
              this.verifyManifest(
                parsedHeader.header,
                manifest,
                documentDescriptor,
                observedAttachments,
              );
            }
          } finally {
            this.crypto.erase(plaintext);
            this.crypto.erase(ciphertext);
            this.crypto.erase(tag);
            this.crypto.erase(nonce);
            this.crypto.erase(aad);
          }
          expectedIndex += 1;
        }

        if (documentBytes === null || currentAttachment !== null || manifest === null) {
          throw new VaultaError('CORRUPT_DATA', 'Der authentifizierte Paketabschluss fehlt.');
        }
        const document = parseAuthenticatedVaultPackageDocument(
          parseJson(documentBytes, 'Der Tresorinhalt im Paket ist ungueltig.'),
        );
        this.validatePackageDocumentReferences(document, attachments, manifest.includesAttachments);
        assertAuthorized?.();
        completed = true;
        return { header: parsedHeader.header, document, attachments, manifest };
      } finally {
        this.crypto.erase(noncePrefix);
      }
    } finally {
      this.crypto.erase(documentBytes);
      this.crypto.erase(headerBytes);
      this.crypto.erase(packageKey);
      this.crypto.erase(passwordKey);
      this.crypto.erase(kdfSalt);
      await input.close().catch(() => undefined);
      if (!completed) {
        for (const attachment of attachments) this.crypto.erase(attachment.plaintext);
        if (currentAttachment !== null) {
          for (const chunk of currentAttachment.chunks) this.crypto.erase(chunk);
        }
      }
    }
  }

  private async readHeader(handle: FileHandle): Promise<{
    header: VaultPackageHeader;
    headerBytes: Buffer;
    dataOffset: number;
  }> {
    const magic = await readExact(handle, PACKAGE_MAGIC.length, 0);
    try {
      if (!this.crypto.equals(magic, PACKAGE_MAGIC)) {
        throw new VaultaError('UNSUPPORTED_FORMAT', 'Die Datei ist kein Kryptris-Tresor-Paket.');
      }
    } finally {
      this.crypto.erase(magic);
    }
    const lengthBytes = await readExact(handle, 4, PACKAGE_MAGIC.length);
    let headerLength: number;
    try {
      headerLength = lengthBytes.readUInt32BE(0);
    } finally {
      this.crypto.erase(lengthBytes);
    }
    if (headerLength === 0 || headerLength > HEADER_LIMIT) {
      throw new VaultaError('CORRUPT_DATA', 'Der Paketheader ist ungueltig.');
    }
    const headerBytes = await readExact(handle, headerLength, PACKAGE_MAGIC.length + 4);
    try {
      return {
        header: this.parseHeader(parseJson(headerBytes, 'Der Paketheader ist beschaedigt.')),
        headerBytes,
        dataOffset: PACKAGE_MAGIC.length + 4 + headerLength,
      };
    } catch (error) {
      this.crypto.erase(headerBytes);
      throw error;
    }
  }

  private parseHeader(value: unknown): VaultPackageHeader {
    if (
      !isRecord(value) ||
      value.format !== 'kryptris-vault-package' ||
      value.version !== VAULT_PACKAGE_FORMAT_VERSION
    ) {
      const version = isRecord(value) && typeof value.version === 'number' ? value.version : null;
      if (version !== null && version > VAULT_PACKAGE_FORMAT_VERSION) {
        throw new VaultaError(
          'UNSUPPORTED_FORMAT',
          `Das Tresor-Paket verwendet die neuere Formatversion ${version}.`,
        );
      }
      throw new VaultaError(
        'UNSUPPORTED_FORMAT',
        'Das Tresor-Paketformat wird nicht unterstuetzt.',
      );
    }
    if (
      typeof value.packageId !== 'string' ||
      !UUID_V4.test(value.packageId) ||
      value.cipher !== 'AES-256-GCM-CHUNKED' ||
      value.chunkSize !== CHUNK_SIZE ||
      typeof value.noncePrefix !== 'string' ||
      !isRecord(value.kdf) ||
      value.kdf.algorithm !== 'argon2id' ||
      typeof value.kdf.salt !== 'string' ||
      !isRecord(value.kdf.parameters)
    ) {
      throw new VaultaError('CORRUPT_DATA', 'Der Paketheader ist ungueltig.');
    }
    assertIsoTimestamp(value.createdAt, 'Der Paketzeitpunkt ist ungueltig.');
    let noncePrefix: Buffer | null = null;
    let salt: Buffer | null = null;
    try {
      noncePrefix = decodeBase64Strict(value.noncePrefix, 8, 'Der Paket-Nonce ist ungueltig.');
      salt = decodeBase64Strict(value.kdf.salt, 16, 'Der Paket-KDF-Salt ist ungueltig.');
      const parameters = this.parseKdfParameters(value.kdf.parameters);
      return {
        format: 'kryptris-vault-package',
        version: VAULT_PACKAGE_FORMAT_VERSION,
        packageId: value.packageId,
        createdAt: value.createdAt,
        cipher: 'AES-256-GCM-CHUNKED',
        chunkSize: CHUNK_SIZE,
        noncePrefix: value.noncePrefix,
        kdf: { algorithm: 'argon2id', salt: value.kdf.salt, parameters },
        wrappedPackageKey: parseEnvelope(value.wrappedPackageKey),
      };
    } finally {
      this.crypto.erase(noncePrefix);
      this.crypto.erase(salt);
    }
  }

  private parseKdfParameters(value: Record<string, unknown>): Argon2idParameters {
    if (
      value.algorithm !== 'argon2id' ||
      typeof value.memorySizeKiB !== 'number' ||
      typeof value.iterations !== 'number' ||
      typeof value.parallelism !== 'number' ||
      value.hashLength !== 32
    ) {
      throw new VaultaError('CORRUPT_DATA', 'Die Paket-KDF-Parameter sind ungueltig.');
    }
    const parameters: Argon2idParameters = {
      algorithm: 'argon2id',
      memorySizeKiB: value.memorySizeKiB,
      iterations: value.iterations,
      parallelism: value.parallelism,
      hashLength: 32,
    };
    try {
      this.keyDerivation.validateParameters(parameters);
      return parameters;
    } catch (error) {
      throw new VaultaError('CORRUPT_DATA', 'Die Paket-KDF-Parameter sind ungueltig.', null, {
        cause: error,
      });
    }
  }

  private parseAttachmentStart(value: unknown): PackageAttachmentStart {
    if (!isRecord(value) || typeof value.id !== 'string' || !isRecord(value.metadata)) {
      throw new VaultaError('CORRUPT_DATA', 'Der Anhangsanfang ist ungueltig.');
    }
    const metadata = this.parseAttachmentMetadata(value.metadata);
    if (metadata.id !== value.id) {
      throw new VaultaError(
        'CORRUPT_DATA',
        'Die Anhangs-ID stimmt nicht mit den Metadaten ueberein.',
      );
    }
    return { id: value.id, metadata };
  }

  private parseAttachmentEnd(value: unknown): PackageAttachmentEnd {
    const id = isRecord(value) ? value.id : undefined;
    const sha256 = isRecord(value) ? value.sha256 : undefined;
    if (
      !isRecord(value) ||
      typeof id !== 'string' ||
      typeof sha256 !== 'string' ||
      !SHA256.test(sha256)
    ) {
      throw new VaultaError('CORRUPT_DATA', 'Der Anhangsabschluss ist ungueltig.');
    }
    assertSafeIdentifier(id, 'Anhangs-ID');
    assertPositiveSafeInteger(value.size, 'Die Anhangsgroesse ist ungueltig.');
    return { id, size: value.size, sha256 };
  }

  private parseAttachmentMetadata(value: Record<string, unknown>): AttachmentMetadata {
    if (
      typeof value.id !== 'string' ||
      typeof value.name !== 'string' ||
      typeof value.mediaType !== 'string' ||
      typeof value.sha256 !== 'string' ||
      typeof value.createdAt !== 'string' ||
      typeof value.previewable !== 'boolean' ||
      !SHA256.test(value.sha256) ||
      value.name.length === 0 ||
      value.name.length > 255 ||
      [...value.name].some((character) => character.charCodeAt(0) < 32) ||
      value.mediaType.length === 0 ||
      value.mediaType.length > 127
    ) {
      throw new VaultaError('CORRUPT_DATA', 'Die Paket-Anhangsmetadaten sind ungueltig.');
    }
    assertSafeIdentifier(value.id, 'Anhangs-ID');
    assertPositiveSafeInteger(value.size, 'Die Anhangsgroesse ist ungueltig.');
    if (value.size > MAX_ATTACHMENT_BYTES) {
      throw new VaultaError(
        'FILE_TOO_LARGE',
        'Ein Paket-Anhang ueberschreitet das unterstuetzte Limit.',
      );
    }
    assertIsoTimestamp(value.createdAt, 'Der Anhangszeitpunkt ist ungueltig.');
    return {
      id: value.id,
      name: value.name,
      mediaType: value.mediaType,
      size: value.size,
      sha256: value.sha256,
      createdAt: value.createdAt,
      previewable: value.previewable,
    };
  }

  private parseManifest(value: unknown): VaultPackageManifest {
    const packageId = isRecord(value) ? value.packageId : undefined;
    const exportedAt = isRecord(value) ? value.exportedAt : undefined;
    const includesAttachments = isRecord(value) ? value.includesAttachments : undefined;
    const rootSha256 = isRecord(value) ? value.rootSha256 : undefined;
    if (
      !isRecord(value) ||
      value.format !== 'kryptris-vault-package-manifest' ||
      value.version !== VAULT_PACKAGE_FORMAT_VERSION ||
      typeof packageId !== 'string' ||
      !UUID_V4.test(packageId) ||
      typeof includesAttachments !== 'boolean' ||
      !isRecord(value.document) ||
      !Array.isArray(value.attachments) ||
      typeof rootSha256 !== 'string' ||
      !SHA256.test(rootSha256)
    ) {
      throw new VaultaError('CORRUPT_DATA', 'Das Paketmanifest ist ungueltig.');
    }
    assertIsoTimestamp(exportedAt, 'Der Paketzeitpunkt ist ungueltig.');
    const document = this.parseDescriptor(value.document);
    const attachments = value.attachments.map((candidate) =>
      this.parseAttachmentDescriptor(candidate),
    );
    const seen = new Set<string>();
    for (const attachment of attachments) {
      if (seen.has(attachment.id)) {
        throw new VaultaError('CORRUPT_DATA', 'Das Paketmanifest enthaelt doppelte Anhangs-IDs.');
      }
      seen.add(attachment.id);
    }
    return {
      format: 'kryptris-vault-package-manifest',
      version: VAULT_PACKAGE_FORMAT_VERSION,
      packageId,
      exportedAt,
      includesAttachments,
      document,
      attachments,
      rootSha256,
    };
  }

  private parseDescriptor(value: Record<string, unknown>): VaultPackageDocumentDescriptor {
    const sha256 = value.sha256;
    if (typeof sha256 !== 'string' || !SHA256.test(sha256)) {
      throw new VaultaError('CORRUPT_DATA', 'Ein Paket-Manifestwert ist ungueltig.');
    }
    assertPositiveSafeInteger(value.size, 'Ein Paket-Manifestwert ist ungueltig.');
    const size = value.size;
    if (size > MAX_METADATA_RECORD_BYTES) {
      throw new VaultaError('FILE_TOO_LARGE', 'Der Tresorinhalt im Paket ist zu gross.');
    }
    return { size, sha256 };
  }

  private parseAttachmentDescriptor(value: unknown): VaultPackageAttachmentDescriptor {
    if (!isRecord(value) || typeof value.id !== 'string') {
      throw new VaultaError('CORRUPT_DATA', 'Ein Paket-Anhangsmanifestwert ist ungueltig.');
    }
    assertSafeIdentifier(value.id, 'Anhangs-ID');
    const descriptor = this.parseDescriptor(value);
    if (descriptor.size > MAX_ATTACHMENT_BYTES) {
      throw new VaultaError(
        'FILE_TOO_LARGE',
        'Ein Paket-Anhang ueberschreitet das unterstuetzte Limit.',
      );
    }
    return { id: value.id, ...descriptor };
  }

  private verifyManifest(
    header: VaultPackageHeader,
    manifest: VaultPackageManifest,
    document: VaultPackageDocumentDescriptor,
    attachments: readonly VaultPackageAttachmentDescriptor[],
  ): void {
    if (
      manifest.packageId !== header.packageId ||
      manifest.exportedAt !== header.createdAt ||
      JSON.stringify(manifest.document) !== JSON.stringify(document) ||
      JSON.stringify(manifest.attachments) !== JSON.stringify(attachments) ||
      manifest.rootSha256 !== this.manifestRootHash(document, attachments)
    ) {
      throw new VaultaError(
        'CORRUPT_DATA',
        'Das Paketmanifest stimmt nicht mit den Daten ueberein.',
      );
    }
    if (!manifest.includesAttachments && attachments.length !== 0) {
      throw new VaultaError('CORRUPT_DATA', 'Ein Paket ohne Anhaenge enthaelt Anhangsdaten.');
    }
  }

  private validatePackageDocumentReferences(
    document: VaultDocument,
    attachments: readonly DecodedAttachment[],
    includesAttachments: boolean,
  ): void {
    const knownFolders = new Set(document.folders.map((folder) => folder.id));
    if (knownFolders.size !== document.folders.length) {
      throw new VaultaError('CORRUPT_DATA', 'Der Paket-Tresor enthaelt doppelte Ordner-IDs.');
    }
    const knownEntries = new Set<string>();
    const expected = new Map<string, AttachmentMetadata>();
    for (const entry of document.entries) {
      if (knownEntries.has(entry.id)) {
        throw new VaultaError('CORRUPT_DATA', 'Der Paket-Tresor enthaelt doppelte Eintrags-IDs.');
      }
      knownEntries.add(entry.id);
      if (entry.vaultId !== document.id) {
        throw new VaultaError(
          'CORRUPT_DATA',
          'Ein Paket-Eintrag gehoert nicht zum enthaltenen Tresor.',
        );
      }
      if (entry.folderId !== null && !knownFolders.has(entry.folderId)) {
        throw new VaultaError(
          'CORRUPT_DATA',
          'Ein Paket-Eintrag verweist auf einen unbekannten Ordner.',
        );
      }
      for (const metadata of entry.attachments) {
        const previous = expected.get(metadata.id);
        if (previous !== undefined) {
          if (!sameAttachmentMetadata(previous, metadata)) {
            throw new VaultaError(
              'CORRUPT_DATA',
              'Ein Paket-Anhang besitzt widerspruechliche Metadaten.',
            );
          }
          throw new VaultaError('CORRUPT_DATA', 'Ein Paket-Anhang wird mehrfach referenziert.');
        }
        expected.set(metadata.id, metadata);
      }
    }
    if (!includesAttachments && expected.size !== 0) {
      throw new VaultaError('CORRUPT_DATA', 'Ein Paket ohne Anhaenge enthaelt Anhangsreferenzen.');
    }
    if (expected.size !== attachments.length) {
      throw new VaultaError(
        'CORRUPT_DATA',
        'Paket-Anhangsdaten und Tresorreferenzen stimmen nicht ueberein.',
      );
    }
    for (const attachment of attachments) {
      const metadata = expected.get(attachment.metadata.id);
      if (metadata === undefined || !sameAttachmentMetadata(metadata, attachment.metadata)) {
        throw new VaultaError(
          'CORRUPT_DATA',
          'Paket-Anhangsdaten und Tresorreferenzen stimmen nicht ueberein.',
        );
      }
    }
  }

  private documentForExport(document: VaultDocument, includeAttachments: boolean): VaultDocument {
    const copy = structuredClone(document);
    if (!includeAttachments) {
      for (const entry of copy.entries) entry.attachments = [];
    }
    parseVaultDocumentV2(copy, copy.id);
    return copy;
  }

  private collectDocumentAttachments(document: VaultDocument): AttachmentMetadata[] {
    const collected = new Map<string, AttachmentMetadata>();
    let total = 0;
    for (const entry of document.entries) {
      for (const metadata of entry.attachments) {
        const previous = collected.get(metadata.id);
        if (previous !== undefined) {
          if (!sameAttachmentMetadata(previous, metadata)) {
            throw new VaultaError(
              'CORRUPT_DATA',
              'Ein Anhang besitzt widerspruechliche Metadaten.',
            );
          }
          throw new VaultaError('CONFLICT', 'Ein Anhang wird mehrfach referenziert.');
        }
        const parsed = this.parseAttachmentMetadata(metadata as unknown as Record<string, unknown>);
        total += parsed.size;
        if (total > this.maximumTotalAttachmentBytes) {
          throw new VaultaError(
            'FILE_TOO_LARGE',
            'Die Anhaenge dieses Tresor-Pakets ueberschreiten das unterstuetzte Gesamtlimit.',
          );
        }
        collected.set(parsed.id, parsed);
      }
    }
    return [...collected.values()].sort((left, right) => left.id.localeCompare(right.id));
  }

  private reidentifyDocument(
    source: VaultDocument,
    attachments: readonly DecodedAttachment[],
    targetVaultId: string,
    targetName: string,
  ): { document: VaultDocument; attachments: PreparedVaultPackageAttachment[] } {
    const allocated = new Set<string>([targetVaultId]);
    const next = (label: string): string => this.nextSafeUniqueId(allocated, label);
    const folderIds = new Map(source.folders.map((folder) => [folder.id, next('Ordner-ID')]));
    const attachmentIds = new Map(
      attachments.map((attachment) => [attachment.metadata.id, next('Anhangs-ID')]),
    );
    const now = this.now().toISOString();
    const remappedAttachments = attachments.map((attachment) => {
      const id = attachmentIds.get(attachment.metadata.id);
      if (id === undefined) throw new VaultaError('INTERNAL', 'Die Anhangszuordnung fehlt.');
      return {
        attachmentId: id,
        name: attachment.metadata.name,
        mediaType: attachment.metadata.mediaType,
        size: attachment.metadata.size,
        sha256: attachment.metadata.sha256,
        createdAt: attachment.metadata.createdAt,
        previewable: isSafeAttachmentPreviewMediaType(attachment.metadata.mediaType),
        contents: attachment.plaintext,
      };
    });
    const document: VaultDocument = {
      ...structuredClone(source),
      id: targetVaultId,
      name: targetName,
      updatedAt: now,
      folders: source.folders.map((folder) => ({
        ...folder,
        id: this.requireMappedId(folderIds, folder.id, 'Ordner-ID'),
      })),
      entries: source.entries.map((entry) => ({
        ...entry,
        id: next('Eintrags-ID'),
        vaultId: targetVaultId,
        folderId:
          entry.folderId === null
            ? null
            : this.requireMappedId(folderIds, entry.folderId, 'Ordner-ID'),
        attachments: entry.attachments.map((metadata) => ({
          ...metadata,
          id: this.requireMappedId(attachmentIds, metadata.id, 'Anhangs-ID'),
          previewable: isSafeAttachmentPreviewMediaType(metadata.mediaType),
        })),
      })),
    };
    parseVaultDocumentV2(document, targetVaultId);
    return { document, attachments: remappedAttachments };
  }

  private toPreview(
    decoded: DecodedPackage,
    existingVaultNames: readonly string[],
  ): VaultPackagePreview {
    return {
      createdAt: decoded.header.createdAt,
      vaultName: decoded.document.name,
      color: decoded.document.color,
      entryCount: decoded.document.entries.length,
      attachmentCount: decoded.attachments.length,
      includesAttachments: decoded.manifest.includesAttachments,
      nameConflict: existingVaultNames.some(
        (name) => normalizedName(name) === normalizedName(decoded.document.name),
      ),
    };
  }

  private descriptor(bytes: Buffer): VaultPackageDocumentDescriptor {
    return { size: bytes.length, sha256: this.crypto.sha256(bytes).toString('hex') };
  }

  private manifestRootHash(
    document: VaultPackageDocumentDescriptor,
    attachments: readonly VaultPackageAttachmentDescriptor[],
  ): string {
    return this.crypto
      .sha256(Buffer.from(JSON.stringify({ document, attachments }), 'utf8'))
      .toString('hex');
  }

  private async writeRecord(
    output: FileHandle,
    position: number,
    type: number,
    index: number,
    plaintext: Buffer,
    packageKey: Buffer,
    noncePrefix: Buffer,
    headerBytes: Buffer,
  ): Promise<number> {
    if (index >= 0xffffffff) {
      throw new VaultaError('FILE_TOO_LARGE', 'Das Tresor-Paket enthaelt zu viele Datensaetze.');
    }
    let nonce: Buffer | null = null;
    let aad: Buffer | null = null;
    let ciphertext: Buffer | null = null;
    let tag: Buffer | null = null;
    let recordHeader: Buffer | null = null;
    try {
      nonce = this.recordNonce(noncePrefix, index);
      aad = this.recordAad(headerBytes, type, index);
      const envelope = this.crypto.encryptWithNonce(plaintext, packageKey, aad, nonce);
      ciphertext = Buffer.from(envelope.ciphertext, 'base64');
      tag = Buffer.from(envelope.tag, 'base64');
      recordHeader = Buffer.allocUnsafe(RECORD_HEADER_BYTES);
      recordHeader.writeUInt8(type, 0);
      recordHeader.writeUInt32BE(index, 1);
      recordHeader.writeUInt32BE(ciphertext.length, 5);
      let next = await writeAll(output, recordHeader, position);
      next = await writeAll(output, tag, next);
      return await writeAll(output, ciphertext, next);
    } finally {
      this.crypto.erase(recordHeader);
      this.crypto.erase(tag);
      this.crypto.erase(ciphertext);
      this.crypto.erase(aad);
      this.crypto.erase(nonce);
    }
  }

  private recordNonce(prefix: Buffer, index: number): Buffer {
    const nonce = Buffer.allocUnsafe(12);
    prefix.copy(nonce, 0);
    nonce.writeUInt32BE(index, 8);
    return nonce;
  }

  private recordAad(headerBytes: Buffer, type: number, index: number): Buffer {
    const record = Buffer.allocUnsafe(5);
    try {
      record.writeUInt8(type, 0);
      record.writeUInt32BE(index, 1);
      return Buffer.concat([
        Buffer.from('kryptris:vault-package-record:v1', 'utf8'),
        this.crypto.sha256(headerBytes),
        record,
      ]);
    } finally {
      this.crypto.erase(record);
    }
  }

  private packageKeyContext(packageId: string): string {
    return `kryptris-vault-package:${packageId}:v${VAULT_PACKAGE_FORMAT_VERSION}:content-key`;
  }

  private async resolveExportDestination(
    destination: string,
    replaceExisting: boolean | undefined,
  ): Promise<string> {
    if (
      typeof destination !== 'string' ||
      destination.trim().length === 0 ||
      !path.isAbsolute(destination)
    ) {
      throw new VaultaError('INVALID_INPUT', 'Der Zielpfad des Tresor-Pakets ist ungueltig.');
    }
    const resolved = path.resolve(destination);
    if (!resolved.toLocaleLowerCase('en-US').endsWith(VAULT_PACKAGE_EXTENSION)) {
      throw new VaultaError(
        'INVALID_INPUT',
        'Das Tresor-Paket muss die Endung .kryptris-vault besitzen.',
      );
    }
    await this.assertSafeExportTarget(resolved, replaceExisting);
    return resolved;
  }

  private async assertSafeExportTarget(
    target: string,
    replaceExisting: boolean | undefined,
  ): Promise<void> {
    await lstat(target).then(
      (info) => {
        if (info.isSymbolicLink() || !info.isFile()) {
          throw new VaultaError(
            'UNSAFE_PATH',
            'Das Ziel des Tresor-Pakets ist keine regulaere Datei.',
          );
        }
        if (replaceExisting !== true) {
          throw new VaultaError('CONFLICT', 'Am Ziel existiert bereits ein Tresor-Paket.');
        }
      },
      (error: NodeJS.ErrnoException) => {
        if (error.code !== 'ENOENT') throw error;
      },
    );
  }

  private async assertRegularPackagePath(
    packagePath: string,
    allowAtomicTemporary = false,
  ): Promise<{ path: string; identity: FileIdentity }> {
    if (
      typeof packagePath !== 'string' ||
      packagePath.trim().length === 0 ||
      !path.isAbsolute(packagePath)
    ) {
      throw new VaultaError('INVALID_INPUT', 'Der Pfad des Tresor-Pakets ist ungueltig.');
    }
    const resolved = path.resolve(packagePath);
    if (
      !resolved.toLocaleLowerCase('en-US').endsWith(VAULT_PACKAGE_EXTENSION) &&
      !(allowAtomicTemporary && ATOMIC_PACKAGE_TEMPORARY.test(path.basename(resolved)))
    ) {
      throw new VaultaError(
        'UNSUPPORTED_FORMAT',
        'Die Datei besitzt kein Kryptris-Tresor-Paketformat.',
      );
    }
    try {
      const info = await lstat(resolved);
      if (info.isSymbolicLink() || !info.isFile()) {
        throw new VaultaError('UNSAFE_PATH', 'Das Tresor-Paket ist keine regulaere Datei.');
      }
      const information = await stat(resolved);
      if (!information.isFile() || information.size < PACKAGE_MAGIC.length + 4) {
        throw new VaultaError('CORRUPT_DATA', 'Das Tresor-Paket ist unvollstaendig.');
      }
      if (!sameIdentity(fileIdentity(info), fileIdentity(information))) {
        throw new VaultaError('CONFLICT', 'Das Tresor-Paket wurde vor dem Einlesen ausgetauscht.');
      }
      return { path: resolved, identity: fileIdentity(info) };
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        throw new VaultaError('NOT_FOUND', 'Das Tresor-Paket wurde nicht gefunden.');
      }
      throw error;
    }
  }

  private async assertOpenedPackageMatches(
    expected: { path: string; identity: FileIdentity },
    opened: Stats,
  ): Promise<void> {
    const current = await lstat(expected.path);
    if (
      current.isSymbolicLink() ||
      !current.isFile() ||
      !sameIdentity(expected.identity, fileIdentity(opened)) ||
      !sameIdentity(expected.identity, fileIdentity(current))
    ) {
      throw new VaultaError('CONFLICT', 'Das Tresor-Paket wurde vor dem Einlesen ausgetauscht.');
    }
  }

  private assertExportInput(input: ExportVaultPackageInput): void {
    assertSafeIdentifier(input.vaultId, 'Tresor-ID');
    this.assertPassword(input.exportPassword);
    if (input.includeAttachments !== true && input.includeAttachments !== false) {
      throw new VaultaError('INVALID_INPUT', 'Die Anhangsauswahl des Tresor-Pakets ist ungueltig.');
    }
  }

  private assertInspectionInput(input: InspectVaultPackageInput): void {
    this.assertPassword(input.exportPassword);
    if (
      input.existingVaultNames !== undefined &&
      (!Array.isArray(input.existingVaultNames) ||
        input.existingVaultNames.some((name) => typeof name !== 'string' || name.length > 100))
    ) {
      throw new VaultaError('INVALID_INPUT', 'Die vorhandenen Tresornamen sind ungueltig.');
    }
  }

  private assertPassword(value: string): void {
    if (typeof value !== 'string' || value.length === 0 || value.length > 4_096) {
      throw new VaultaError(
        'INVALID_INPUT',
        'Das Exportpasswort muss 1 bis 4096 Zeichen lang sein.',
      );
    }
  }

  private validateVaultName(value: string): string {
    if (typeof value !== 'string') {
      throw new VaultaError('INVALID_INPUT', 'Der Ziel-Tresorname ist ungueltig.');
    }
    const normalized = value.trim();
    if (normalized.length === 0 || normalized.length > 100) {
      throw new VaultaError(
        'INVALID_INPUT',
        'Der Ziel-Tresorname muss 1 bis 100 Zeichen lang sein.',
      );
    }
    return normalized;
  }

  private nextPackageId(): string {
    const id = this.generateId();
    if (!UUID_V4.test(id)) {
      throw new VaultaError('INTERNAL', 'Die erzeugte Paket-ID ist ungueltig.');
    }
    return id;
  }

  private nextSafeUniqueId(allocated: Set<string>, label: string): string {
    for (let attempts = 0; attempts < 128; attempts += 1) {
      const id = this.generateId();
      try {
        assertSafeIdentifier(id, label);
      } catch (error) {
        if (error instanceof VaultaError) continue;
        throw error;
      }
      if (!allocated.has(id)) {
        allocated.add(id);
        return id;
      }
    }
    throw new VaultaError('INTERNAL', 'Eine neue technische ID konnte nicht erzeugt werden.');
  }

  private requireMappedId(mapping: ReadonlyMap<string, string>, id: string, label: string): string {
    const mapped = mapping.get(id);
    if (mapped === undefined) {
      throw new VaultaError('CORRUPT_DATA', `Die ${label} konnte nicht zugeordnet werden.`);
    }
    return mapped;
  }

  private disposeDecoded(decoded: DecodedPackage | null): void {
    if (decoded === null) return;
    for (const attachment of decoded.attachments) this.crypto.erase(attachment.plaintext);
  }

  private redactUnexpectedError(error: unknown, message: string): VaultaError {
    if (error instanceof VaultaError) return error;
    return new VaultaError('INTERNAL', message, 'Versuche die Aktion erneut.', { cause: error });
  }
}
